version: '3'

services:
    db:
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_USER=locale_test
            - POSTGRES_PASSWORD=locale-test
            - POSTGRES_DB=locale_task

    web:
        build: ./api
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis

    redis:
        build: ./misc/redis
        ports:
            - "6379:6379"


    celery:
        build: ./misc/celery
        depends_on:
            - redis
