version: '3'

services:
    db:
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=atlan_task

    web:
        build: ./api
        command: bash -c "python manage.py migrate && python manage.py loaddata ./fixtures/customer.json && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    celery:
        build: ./api
        command: celery worker -A api.celery -c 4 -l INFO
        depends_on:
            - web
