openapi: 3.0.3

info:
  title: "Locale Backend Task"
  version: '1.0.0'

servers:
  - url: /api/v1

paths:
  # Database entities
  /bookings:
    post:
      summary: Create a new booking
      tags: [bookings]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bookings'
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking_id:
                    type: string
                    format: uuid
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/Unknown'

components:
  # Reusable schemas (data models)
  schemas:
    # Database entities
    Bookings:
      description: >
        Bookings
      type: object
      properties:
        booking_id:
          type: string
          format: uuid
          description: The booking ID.
        user_id:
          type: string
          format: uuid
          description: The user id.
        vehicle_model_id:
          type: integer
          description: The vehicle model id.
        package_id:
          type: integer
          description: The package id.
        travel_type_id:
          type: integer
          description: The travel type id.
        to_area_id:
          type: integer
          description: The destination area id.
        from_city_id:
          type: integer
          description: The orign city id.
        to_city_id:
          type: integer
          description: The destination city id.
        from_date:
          type: string
          format: date-time
          description: From date of the booking.
        to_date:
          type: string
          format: date-time
          description: To date of the booking.
        online_booking:
          type: boolean
          description: Boolean if its an online booking.
        car_cancellation:
          type: boolean
          description: Boolean if the booking is cancelled.
        to_long:
          type: number
          format: double
          description: Destination's longitude.
        to_lat:
          type: number
          format: double
          description: Destination's latitude.
        from_long:
          type: number
          format: double
          description: Origin's longitude.
        from_lat:
          type: number
          format: double
          description: Origin's latitude.
        booking_created:
          type: boolean
          description: Boolean if the booking is created.
        mobile_site_booking:
          type: boolean
          description: Boolean if the booking is done through the mobile site.

    Error:
      description: |
        [RFC7807](https://tools.ietf.org/html/rfc7807) compliant response.
      type: object
      properties:
        type:
          type: string
          description: |
            A URI reference [RFC3986] that identifies the problem type. This specification
            encourages that, when dereferenced, it provide human-readable documentation for
            the problem type.
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: number
          description: The HTTP status code generated by the API server for this occurrence of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          description: |
            A URI reference that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
      required:
        - type
        - title
        - status

  responses:
    # 400
    'BadRequest':
      description: Client specified an invalid argument.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    # 500
    'Unknown':
      description: Unknown server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
